function randomText() {
  var randomNum = Math.round(Math.random() * 10);
  var quotes = [
    "“Each of us is a unique strand in the intricate web of life and here to make a contribution.”",
    `“Too many things on my mind, said Wilbur.
Well, said the goose, that's not my trouble. I have nothing at all on my mind, but I've too many things under my behind.”`,
    `“I clung to each word that fell from his lips like a spider to a web.”`,
    `“I’m going to untangle her deadly scheme, even if it leaves my love affair hanging by a thread.”`,
    `“Meestal zijn er grote delen van de pagina die niet eens bekeken worden door de bezoeker! Hij keurt ze letterlijk geen blik waardig.”`,
    `Your legs spin luminous webs that I still get stuck in every single time.”`,
    `“It is not called 'The Web' for any small reason. It was declared to you right at the start that this is going to be a web.”`,
    `“Weißt du eigentlich, warum man es >das Netz< nennt?" - “Weil wir darin gefangen sind.”`,
    `“Narcissists, however, are similar to a spider that has built a web for its prey to bring itself.”`,
    `“Many of the criminal skills on the Web have emerged from an essential division in the philosophical debate generated by the Internet.`,
    `“Many of the criminal skills on the Web have emerged from an essential division in the philosophical debate generated by the Internet.`,
  ];
  var authors = [
    "― Deepak Chopra",
    `― E. B. White, Charlotte's Web`,
    `― Dannika Dark, Twist`,
    `― Jennifer Estep, Widow's Web`,
    `― Peter Kassenaar`,
    `― Curtis Tyrone Jones`,
    `― Vineet Raj Kapoor`,
    `― Marc-Uwe Kling`,
    `― Mwanandeke Kindembo`,
    `― Misha Glenny`,
    `― Misha Glenny`,
  ];
  document.getElementById("quote").innerHTML = quotes[randomNum];
  document.getElementById("author").innerHTML = authors[randomNum];
}
